import React from 'react';

function Seat(props) {

    const soLuongChoNgoi = 101; // Số lượng chỗ ngồi

    // Tạo một mảng JSX chứa các chỗ ngồi
    const choNgoi = [];
    for (let i = 1; i <= soLuongChoNgoi; i++) {
        choNgoi.push(
            <div className="bg-red-800 rounded-full w-5 text-center" key={i}>{i}</div>
        );
    }

    return (
        <>
            <div className="bg-white mt-3 pt-3 overflow-y-auto">
                <h1 className="py-3 mx-auto rounded-full w-3/4 text-center font-bold text-3xl bg-[#EDEDED] ">Sân
                    khấu/Stage</h1>
                <div className="mx-auto my-4 ">
                    <div className="bg-[#FFD5CF] px-2 pt-2 pb-4 rounded-t-lg	">
                        <div className="flex items-center justify-center gap-3 mt-3">

                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                    </div>
                    <div className="bg-[#C4F1F2] px-2 pt-1 pb-4">
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                    </div>
                    <div className="bg-[#FDE098] px-2 pt-1 pb-4 rounded-b-lg ">
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                        <div className="flex items-center justify-center gap-3 mt-3">
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                            <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                        </div>
                    </div>
                </div>


            </div>
        </>
    );
}


export default Seat;
