import React from 'react';

function Seat(props) {

    const soLuongChoNgoi = 101; // Số lượng chỗ ngồi

    // Tạo một mảng JSX chứa các chỗ ngồi
    const choNgoi = [];
    for (let i = 1; i <= soLuongChoNgoi; i++) {
        choNgoi.push(
            <div className="bg-red-800 rounded-full w-5 text-center" key={i}>{i}</div>
        );
    }

    return (
        <>
            <div className="bg-white mt-3 pt-3 overflow-y-auto">
                <h1 className="py-3 mx-auto rounded-full w-3/4 text-center font-bold text-3xl bg-[#EDEDED] ">Sân
                    khấu/Stage</h1>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
                <div className="flex items-center justify-center gap-3 mt-3">
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">1</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">2</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">3</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">4</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">5</div>
                    <div className="bg-red-600 rounded-full w-5 text-center">6</div>
                </div>
            </div>
        </>
    );
}


export default Seat;
